server.tomcat.so-linger=-1
server.address=0.0.0.0
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sheetalagarwal528@gmail.com
# Note: This must be an "App Password" generated in your Google Account security settings, not your actual login password.
spring.mail.password=sxka wciy rnoi utjy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.datasource.url=jdbc:postgresql://localhost:5432/mittal_uniform_db
spring.datasource.username=postgres
spring.datasource.password=Sheetu1404*
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / HIBERNATE BEHAVIOR ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Force Hibernate to talk in PostgreSQL's native SQL dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

mittal.uniforms.otp-expiry-minutes=30